---
title: "Resumen CNAA XV"
author: "Marion Díaz"
date: "2024-10-14"
output:
  word_document: default
  html_document: default
  pdf_document: default
---


```{r cargar paquetes}

library(tidyverse)
library(lubridate)
library(ggrepel)
library(Cairo)
library(gt)
library(webshot2)
library(dplyr)
library(tidyr)
```

```{r Leer y limpiar datos generales}
data <- read.csv("datos cnaa oct 2024.csv")
sitios <- read.csv("SitiosCNAAsep24.csv")

#incluye .sp
especies <- read.csv("especies censables cnaa.csv")
especies <- especies %>% 
  mutate(Scientific.Name = scientific_name)

#remover subespecies y solo dejar especies censables 
especies_limpio <- read.csv("especies censables cnaa limpio.csv")
especies_limpio <- especies_limpio %>% 
  mutate(Scientific.Name = scientific_name)

#limpiar y transformar datos
data <- data %>% 
  mutate(Date = as.Date(Date), Count = as.numeric(Count), Common.Name = as.factor(Common.Name), Scientific.Name = as.factor(Scientific.Name), Región = as.factor(State.Province), Location = as.factor(Location)) %>% 
  inner_join(especies_limpio, by = 'Scientific.Name') %>% 
  droplevels()

sitios <- sitios %>% 
  rename('Location' = 'Lugar')
  
#ordenar regiones
levels(data$Región)<- c('Aysén', 'Antofagasta', 'Arica y Parinacota','Araucanía', 'Atacama', 'Bío-Bío', 'Coquimbo', "O'Higgins",'Los Lagos', 'Los Ríos', 'Magallanes', 'Maule', 'Ñuble', 'Metropolitana', 'Tarapacá', 'Valparaíso')
data$Región <- factor(data$Región, levels = c('Arica y Parinacota','Tarapacá', 'Antofagasta', 'Atacama','Coquimbo','Valparaíso', 'Metropolitana',"O'Higgins",'Maule', 'Ñuble','Bío-Bío','Araucanía', 'Los Ríos','Los Lagos', 'Aysén','Magallanes'))

# Filtrar los datos usando los sitios prioritarios 
data <- data %>%
  filter(Location %in% sitios$Location) %>%
  droplevels()
```

```{r Arica y Parinacota}

XV <- filter(data, Región == "Arica y Parinacota")

#separar datos para verano e invierno 
data_verano <- XV%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XV%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza XV CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XV CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XV CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2017`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2017`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2017`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2017`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2018`, `2019`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs XV CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs XV CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs XV CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs XV CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs XV CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs XV CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2018`, `2019`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2017`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios XV CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XV CNAA oct 2024 inv.png")
```

```{r Tarapacá}

I <- filter(data, Región == "Tarapacá")

#separar datos para verano e invierno 
data_verano <- I%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- I%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, 3)

ggsave("Riqueza I CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia I CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios I CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2021`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2021`) %>%
  arrange(`Especie`) 

SPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2021`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2012`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2012`) %>%  
  arrange(`Especie`) 

SPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2012`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver

gtsave(SPs_region_ver, file = "SPs I CNAA oct 2024 ver.png")
gtsave(SPs_region_inv, file = "SPs I CNAA oct 2024 inv.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2012`) %>%
  mutate(Total = rowSums(across(`2010`:`2012`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2021`) %>%
  mutate(Total = rowSums(across(`2009`:`2021`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios I CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios I CNAA oct 2024 inv.png")
```

```{r Antofagasta}

II <- filter(data, Región == "Antofagasta")

#separar datos para verano e invierno 
data_verano <- II%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- II%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza II CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia II CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios II CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2014`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2013`, `2014`) %>%
  arrange(`Especie`) 

SPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2013`, `2014`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2016`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2015`, `2016`) %>%  
  arrange(`Especie`) 

SPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2015`, `2016`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver

gtsave(SPs_region_ver, file = "SPs II CNAA oct 2024 ver.png")
gtsave(SPs_region_inv, file = "SPs II CNAA oct 2024 inv.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2015`, `2016`) %>%
  mutate(Total = rowSums(across(`2010`:`2016`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2013`, `2014`) %>%
  mutate(Total = rowSums(across(`2009`:`2014`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios II CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios II CNAA oct 2024 inv.png")
```

```{r Atacama}

III <- filter(data, Región == "Atacama")

#separar datos para verano e invierno 
data_verano <- III%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- III%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza III CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia III CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios III CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2015`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2013`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs III CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs III CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs III CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs III CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs III CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs III CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2013`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2015`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios III CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios III CNAA oct 2024 inv.png")
```

```{r Coquimbo}

IV <- filter(data, Región == "Coquimbo")

#separar datos para verano e invierno 
data_verano <- IV%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- IV%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza IV CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia IV CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios IV CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs IV CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs IV CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs IV CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs IV CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs IV CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs IV CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios IV CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios IV CNAA oct 2024 inv.png")
```

```{r Valparaíso}

V <- filter(data, Región == "Valparaíso")

#separar datos para verano e invierno 
data_verano <- V %>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- V %>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.85, 0.15))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza V CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia V CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios V CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs V CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs V CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs V CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs V CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs V CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs V CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios V CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios V CNAA oct 2024 inv.png")
```

```{r Metropolitana}

XIII <- filter(data, Región == "Metropolitana")

#separar datos para verano e invierno 
data_verano <- XIII %>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XIII %>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza XIII CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XIII CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XIII CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs XIII CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs XIII CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs XIII CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs XIII CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs XIII CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs XIII CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios XIII CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XIII CNAA oct 2024 inv.png")
```

```{r O'Higgins}

VI <- filter(data, Región == "O'Higgins")

#separar datos para verano e invierno 
data_verano <- VI %>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- VI %>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza VI CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia VI CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios VI CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2023`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs VI CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs VI CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs VI CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs VI CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs VI CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs VI CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`) %>%
  mutate(Total = rowSums(across(`2009`:`2023`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios VI CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios VI CNAA oct 2024 inv.png")
```

```{r Maule}

VII <- filter(data, Región == "Maule")

#separar datos para verano e invierno 
data_verano <- VII%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- VII%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.85, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza VII CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia VII CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios VII CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`,  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c( `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c( `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c( `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs VII CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs VI CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs VII CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs VII CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs VII CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs VII CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`,  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios VII CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios VII CNAA oct 2024 inv.png")
```

```{r Ñuble}

XVI <- filter(data, Región == "Ñuble")

#separar datos para verano e invierno 
data_verano <- XVI%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XVI%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, 2)

ggsave("Riqueza XVI CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XVI CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XVI CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2014`, `2023`, `2024`) %>%
  arrange(`Especie`) 

SPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2014`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2019`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2014`, `2019`) %>%  
  arrange(`Especie`) 

SPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`,  `2014`, `2019`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver

gtsave(SPs_region_ver, file = "SPs XVI CNAA oct 2024 ver.png")
gtsave(SPs_region_inv, file = "SPs XVI CNAA oct 2024 inv.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2014`, `2019`) %>%
  mutate(Total = rowSums(across(`2010`:`2019`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2014`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios XVI CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XVI CNAA oct 2024 inv.png")
```

```{r Bío-Bío}

VIII <- filter(data, Región == "Bío-Bío")

#separar datos para verano e invierno 
data_verano <- VIII%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- VIII%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.5, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza VIII CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia VIII CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios VIII CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2023`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2013`, `2022`, `2023`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2013`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2013`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2013`, `2022`, `2023`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2019`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c( `2010`, `2011`, `2012`, `2013`, `2014`, `2019`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2019`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2019`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs VIII CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs VIII CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs VIII CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs VIII CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs VIII CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs VIII CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`,  `2010`, `2011`, `2012`, `2013`, `2014`, `2019`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2013`, `2022`, `2023`) %>%
  mutate(Total = rowSums(across(`2009`:`2023`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios VIII CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios VIII CNAA oct 2024 inv.png")
```

```{r Araucanía}

IX <- filter(data, Región == "Araucanía")

#separar datos para verano e invierno 
data_verano <- IX%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- IX%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza IX CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia IX CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios IX CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2018`, `2019`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2018`, `2019`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs IX CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs IX CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs IX CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs IX CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs IX CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs IX CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2018`, `2019`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios IX CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios IX CNAA oct 2024 inv.png")
```

```{r Los Ríos}

XIV <- filter(data, Región == "Los Ríos")

#separar datos para verano e invierno 
data_verano <- XIV%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XIV%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.8, 0.2))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza XIV CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XIV CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XIV CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2015`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2015`, `2016`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

SPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2015`, `2016`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2014`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

SPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver

gtsave(SPs_region_ver, file = "SPs XIV CNAA oct 2024 ver.png")
gtsave(SPs_region_inv, file = "SPs XIV CNAA oct 2024 inv.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2014`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`,  `2015`, `2016`, `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2015`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios XIV CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XIV CNAA oct 2024 inv.png")
```

```{r Los Lagos}

X <- filter(data, Región == "Los Lagos")

#separar datos para verano e invierno 
data_verano <- X%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- X%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza X CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia X CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios X CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`,  `2012`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`)  

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2012`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2012`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`,  `2012`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2012`, `2013`, `2014`, `2015`,  `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2012`, `2013`, `2014`, `2015`,  `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2012`, `2013`, `2014`, `2015`,  `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2012`, `2013`, `2014`, `2015`,  `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs X CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs X CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs X CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs X CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs X CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs X CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2012`, `2013`, `2014`, `2015`,  `2018`, `2019`, `2020`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )


replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`,  `2012`, `2013`, `2014`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )

gtsave(Sitios_region_ver, file = "Sitios X CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios X CNAA oct 2024 inv.png")
```

```{r Aysén}

XI <- filter(data, Región == "Aysén")

#separar datos para verano e invierno 
data_verano <- XI%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XI%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza XI CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XI CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XI CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2014`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2014`, `2015`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

SPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2014`, `2015`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2018`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2018`, `2022`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

SPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2018`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver

gtsave(SPs_region_ver, file = "SPs XI CNAA oct 2024 ver.png")
gtsave(SPs_region_inv, file = "SPs XI CNAA oct 2024 inv.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2018`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2018`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )

replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2014`, `2015`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2014`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios XI CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XI CNAA oct 2024 inv.png")
```

```{r Magallanes}

XII <- filter(data, Región == "Magallanes")

#separar datos para verano e invierno 
data_verano <- XII%>% 
  filter(Date >= as.Date(paste(year(Date), 01, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 02, 28, sep = "-")))

data_invierno <- XII%>% 
  filter(Date >= as.Date(paste(year(Date), 06, 15, sep = "-")),
           Date <= as.Date(paste(year(Date), 08, 15, sep = "-")))

#Riqueza
sp_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>%
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sp_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(richness = n_distinct(Common.Name)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sp_all <- rbind(sp_verano,sp_invierno)

sp_plot <- ggplot(sp_all, aes(x = date, y = richness, fill=Censo, col=Censo)) +
  geom_line(linewidth = 1) +
  labs(x = "", y = "N especies") +
  scale_x_continuous(n.breaks = 9)+
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(sp_all$richness))

#Abundancia relativa
ab_verano <- data_verano %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

ab_invierno <- data_invierno %>%
  group_by(year(Date)) %>% 
  summarise(Abundancia = sum(Count, na.rm=T)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

ab_all <- rbind(ab_verano,ab_invierno)

ab_plot <- ggplot(ab_all, aes(x = date, y = Abundancia, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  scale_x_continuous(n.breaks = 9)+
  labs(x = "", y = 'N individuos') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  theme_classic()+
  theme(legend.position = 'none')+
  ylim(0, max(ab_all$Abundancia))

#Censos por temporada por año
sitios_verano <- data_verano %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Verano")

sitios_invierno <- data_invierno %>% 
  group_by(year(Date)) %>% 
  summarise(N = n_distinct(Location)) %>% 
  rename(date='year(Date)')%>%
  mutate(Censo = "Invierno")

sitios_all <- rbind(sitios_verano,sitios_invierno)

sitios_plot <- ggplot(sitios_all, aes(x = date, y = N, fill=Censo, col=Censo)) +
  geom_line(size=1) +
  labs(x = "", y = 'N sitios') +
  scale_color_manual(values=c('Verano' = 'darkorange', 'Invierno' = 'lightblue'))+
  scale_x_continuous(n.breaks = 9)+
  theme_classic()+
  theme(legend.position = c(0.2, 0.8))+
  geom_text_repel(aes(label=N),vjust= -2,  size=3.5,show.legend = F)+
  ylim(0, max(sitios_all$N))

ggsave("Riqueza XII CNAA Oct 2024.png", sp_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Abundancia XII CNAA Oct 2024.png", ab_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")
ggsave("Sitios XII CNAA Oct 2024.png", sitios_plot, width = 4.5, height = 3.5, dpi = 300, type = "cairo")

SPs_region_inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%
  group_by(Common.Name, year(Date)) %>%
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%
  rename(`Especie` = Common.Name) %>%
  mutate(across(`2009`:`2024`, ~replace_na(.x, 0))) %>%
  select(`Especie`, `2009`, `2010`, `2011`, `2012`, `2014`, `2016`, `2017`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  arrange(`Especie`) 

tSPs_region_inv <- SPs_region_inv %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2014`, `2016`, `2017`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_inv

# Divide SPs_region_inv en dos partes
SPs_region_inv_part1 <- SPs_region_inv %>% slice(1:(n() %/% 2))
SPs_region_inv_part2 <- SPs_region_inv %>% slice((n() %/% 2 + 1):n())

SPs_region_inv_part1 <- SPs_region_inv_part1 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2014`, `2016`, `2017`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part1

SPs_region_inv_part2 <- SPs_region_inv_part2 %>%
  gt() %>%
  data_color(
    columns = c(`2009`, `2010`, `2011`, `2012`, `2014`, `2016`, `2017`, `2019`, `2021`, `2022`, `2023`, `2024`),
    method = "numeric",
    palette = "Blues",
    domain = c(0, max(range(SPs_region_inv_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_inv_part2

SPs_region_ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Common.Name, year(Date)) %>% 
  summarise(Total_Count = sum(Count, na.rm = TRUE), .groups = 'drop') %>%  
  pivot_wider(names_from = `year(Date)`, values_from = Total_Count, values_fill = 0) %>%  
  rename(`Especie` = Common.Name) %>%  
  mutate(across(`2010`:`2024`, ~replace_na(.x, 0))) %>%  
  select(`Especie`, `2010`, `2011`, `2012`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2023`, `2024`) %>%  
  arrange(`Especie`) 

tSPs_region_ver <- SPs_region_ver %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver %>% select(-Especie), na.rm = TRUE)))
  )

tSPs_region_ver

# Divide SPs_region_ver en dos partes
SPs_region_ver_part1 <- SPs_region_ver %>% slice(1:(n() %/% 2))
SPs_region_ver_part2 <- SPs_region_ver %>% slice((n() %/% 2 + 1):n())

SPs_region_ver_part1 <- SPs_region_ver_part1 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part1 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part1

SPs_region_ver_part2 <- SPs_region_ver_part2 %>%
  gt() %>% 
  data_color(
    columns = c(`2010`, `2011`, `2012`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2023`, `2024`),
    method = "numeric",
    palette = "Oranges",
    domain = c(0, max(range(SPs_region_ver_part2 %>% select(-Especie), na.rm = TRUE)))
  )

SPs_region_ver_part2

gtsave(tSPs_region_ver, file = "SPs XII CNAA oct 2024 ver.png")
gtsave(tSPs_region_inv, file = "SPs XII CNAA oct 2024 inv.png")
gtsave(SPs_region_ver_part1, file = "SPs XII CNAA oct 2024 ver1.png")
gtsave(SPs_region_ver_part2, file = "SPs XII CNAA oct 2024 ver2.png")
gtsave(SPs_region_inv_part1, file = "SPs XII CNAA oct 2024 inv1.png")
gtsave(SPs_region_inv_part2, file = "SPs XII CNAA oct 2024 inv2.png")

#Sitios censados en la región
replicas.ver <- data_verano %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_ver <- replicas.ver %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2010`, `2011`, `2012`, `2016`, `2017`, `2018`, `2019`, `2020`, `2021`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2010`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Oranges"  
  )

replicas.inv <- data_invierno %>%
  mutate(Date = as.Date(Date)) %>%  
  group_by(Location, year(Date)) %>%  
  summarise(Visitado = n_distinct(Location), .groups = 'drop') %>%  
  mutate(Visitado = ifelse(Visitado > 0, "*", "")) 

Sitios_region_inv <- replicas.inv %>%
  pivot_wider(names_from = `year(Date)`, values_from = Visitado, values_fill = "") %>%  
  rename(`Sitio` = Location) %>%  
  select(`Sitio`, `2009`, `2010`, `2011`, `2012`, `2014`, `2016`, `2017`, `2019`, `2021`, `2022`, `2023`, `2024`) %>%
  mutate(Total = rowSums(across(`2009`:`2024`, ~ . != ""))) %>%
  arrange(`Sitio`) %>%  
  gt() %>% 
  data_color(
    columns = Total,  
    method = "numeric", 
    palette = "Blues"  
  )


gtsave(Sitios_region_ver, file = "Sitios XII CNAA oct 2024 ver.png")
gtsave(Sitios_region_inv, file = "Sitios XII CNAA oct 2024 inv.png")
```
